### ISSUE TITLE
Don’t register a translation provider when no models are available

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/translate#36]
The translate app always registers as a translation provider, even if no models are available. This results in `$this->translationManager->hasProviders()` returning true, even when no provider can actually be used.
This check is used in talk since version 18 (see https://github.com/nextcloud/spreed/pull/10317) and would now need a second check for the available languages to correctly show/hide the translate options on the clients.

**Comment by marcelklehr** [comment]
Why would one install this app without actually installing any models?

**Comment by SystemKeeper** [comment]
> Why would one install this app without actually installing any models?

In general you won’t, I agree. But we actually had that issue on c.nc.c. Nobody noticed that the models were missing. In Talk 18 we changed the way we detect translation availability (since we only include a Boolean in the capabilities when a translation provider is registered and separately fetch the available languages).

**Comment by marcelklehr** [comment]
> Nobody noticed that the models were missing.

I think this is a unique aspect of c.nc.c -- that no admin actually cares properly about the apps that are installed.

**Comment by nickvergessen** [comment]
> that no admin actually cares properly about the apps that are installed.

![grafik](https://github.com/nextcloud/translate/assets/213943/e9c89f0c-5739-481b-98f5-306d6b9e6158)

**Comment by nickvergessen** [comment]
> Why would one install this app without actually installing any models?

Maybe the model was lost on an upgrade/update of the app or something alike? Are they not stored in the apps/ folder? 

If so updating the app from the appstore will remove the directory and copy the newly downloaded appstore app to the place again and the models are gone again?
https://github.com/nextcloud/server/blob/6f39d82031202a2a8d1fb81ea448a2ffdc52cc29/lib/private/Installer.php#L368-L376

**Comment by marcelklehr** [comment]
Ah, yes, that's a problem indeed. But that partly proves my point: people updated the app  without checking if it still works.

**Comment by nickvergessen** [comment]
Well no one expects that updating an app would remove data? On our instance there is a cron job updating apps btw, and I guess we are not the only ones with that 🙃

But I think there was a message now telling that no models are there, or was that from another app?

Maybe sending a notification to admins could be another option? 🤔

**Comment by marcelklehr** [comment]
> Well no one expects that updating an app would remove data?

Definitely. This needs to be fixed. I don't think the solution in OP is the way to go though.

> But I think there was a message now telling that no models are there, or was that from another app?

The admin panel of the app shows a warning.

**Comment by nickvergessen** [comment]
> The admin panel of the app shows a warning.

Maybe this can be turned into one of the new `ISetupCheck`s? https://github.com/nextcloud/server/blob/39d2970191f88b0e9575e170e904a5c2214cb709/lib/public/SetupCheck/ISetupCheck.php#L36
But documentation is still pending, so can only send you to the code: https://github.com/nextcloud/server/pull/32550#issuecomment-1774018498

**Comment by marcelklehr** [comment]
Oh, yeah, this is a nice idea! Thank you!
