### ISSUE TITLE
Text app interface language selector Javascript is broken for me

### ISSUE THREAD

**Issue by khoschi** [nextcloud/translate#49]
- Nextcloud 28.0.5.1
- Node.js v18.12.1 (apps/translate/bin/node)
- App and models installed without issues

When opening a textfile with some text in it with firefox/chrome and access, the translate command via the menu opens a dialog, but the languages can't be changed with the pulldown menus. The left one is locked out and remains on "Detect language", the right blinks shortly a list of languages and closes instantly again. Translations can not be started therefore.

Is this a bug, and if yes, in which module? Or did I miss something?

**Comment by marcelklehr** [comment]
This is a bug in text: https://github.com/nextcloud/text
