### ISSUE TITLE
Dropdown "Target Language" cannot be modified

### ISSUE THREAD

**Issue by juergen852** [nextcloud/translate#52]
I cannot find the reason, why I cannot 
- set "Translate from" language: Dropdown does not react.
- set "to"-Language: Dropdown goes down shortly, but no selection possible.

Installed Languages: de en fr
Text in "Text to translate from" was highlighted before opening Translate.
Hitting "Translate"-Button does nothing.

![grafik](https://github.com/nextcloud/translate/assets/33433306/17eb0a1e-9591-4993-ae18-358476add583)

**Comment by marcelklehr** [comment]
This is a known issue in the text app

**Comment by juergen852** [comment]
OK,  good to know.
Is there a list which indicates, where Translate works?
(We do not use mail or calendar in NC, so I could not find any app, except text, which integrates Translate)

**Comment by marcelklehr** [comment]
Yes, it's here: https://docs.nextcloud.com/server/latest/admin_manual/ai/overview.html#machine-translation

**Comment by juergen852** [comment]
Thanks, I will test.

**Comment by zydisney** [comment]
> This is a known issue in the text app

Is there any mess work can fix this issue? Like edit the css?
