### ISSUE TITLE
Noob question ? How to use ?

### ISSUE THREAD

**Issue by crocobc** [nextcloud/translate#7]
Hi there,

Thank you for the app :)

I installed app, run command to download models => OK
No errors in logs everything seems to be ok.

But i cannot find how to use it ! (not in the smart picker, nothing in the admin section....)

I know silly question but i cannot find any documentation about this anywhere.

Thank you for your answer...

Regards

**Comment by marcelklehr** [comment]
The app does not implement its own interface but only exposes an API to be used by other apps.
Currently, this is only used by the text app.

**Comment by crocobc** [comment]
Very nice :)

Working like a charm. Thank you

Closing
